Excludes inputs

diff --git a/conflictFinder b/conflictFinder
--- a/conflictFinder
+++ b/conflictFinder
@@ -1,14 +1,22 @@
 #!/bin/sh -l
 set -eu
 
-if
-    grep -lr -R --exclude-dir={node_modules,vendor,.git} --exclide={} -E -- '^<<<<<<<|^>>>>>>>' .;
-then
-    printf "\033[1;31mFound merge conflicts.\033[0m\n"
-    exit 1;
-fi
->>>>>>>
+grepExit () {
+	# Grep Returns 1 if not found, > 1 is an error
+	if [ $1 -eq 1 ]; then
+		printf "\033[0;32mNo merge conflicts found.\033[0m\n"
+		exit 0;
+	fi
+	printf "\033[1;31mGrep Error.\033[0m\n"
+	exit 1;
+}
 
-printf "\033[0;32mNo merge conflicts found.\033[0m\n"
-exit 0;
+CONFLICTS="$(grep -lr -R --exclude-dir={.git,"${INPUT_EXCLUDE_DIR}"} --exclude={"${INPUT_EXCLUDES}"} -E -- '^<<<<<<<|^>>>>>>>' .)" || grepExit $?
 
+printf "\033[1;31mFound merge conflicts.\033[0m\n"
+for file in "$CONFLICTS"
+do
+	echo "::error file="$file"::Merge conflict found in $file"
+done
+
+exit 1;
